#!/usr/bin/env python3
"""Verify that a branch carries a legal version step over the branch it targets.

Runs from CI on pull requests into main, so that a release or hotfix cannot reach
main without the version change its release needs. Forgetting the bump otherwise
fails silently: the release workflow finds the tag already present and skips,
producing no release and no error.

Reads the version block out of two copies of CMakeLists.txt rather than taking
version strings directly, so that the parsing matches what CMake itself sees.
"""

# NOTE: this script was generated by Claude for convenience, as it serves no other
# purpose than checking version bumping rules for CI.
# a quick CLEANUP would be nice to have sooner or later, there's lot of unnecessary
# complexity here

import argparse
import re
import sys

VERSION_RE = re.compile(r"project\(ShaderTranspilerCore VERSION (\d+)\.(\d+)\.(\d+)\)")
SUFFIX_RE  = re.compile(r'set\(STC_VERSION_SUFFIX "([^"]*)"\)')
RC_RE      = re.compile(r"^rc\.(\d+)$")

def read_version(path):
    try:
        text = open(path, encoding="utf-8").read()
    except OSError as err:
        sys.exit(f"could not read {path}: {err}")

    version_match = VERSION_RE.search(text)
    if version_match is None:
        sys.exit(f"could not find the project version in {path}")

    suffix_match = SUFFIX_RE.search(text)
    if suffix_match is None:
        sys.exit(f"could not find STC_VERSION_SUFFIX in {path}")

    return tuple(int(part) for part in version_match.groups()), suffix_match.group(1)

def rc_number(suffix, where):
    """The N in rc.N, or None for an empty suffix. Anything else is not a valid suffix."""
    if suffix == "":
        return None

    match = RC_RE.match(suffix)
    if match is None:
        sys.exit(f"invalid version suffix '{suffix}' on {where} (expected empty or rc.N)")

    return int(match.group(1))

def describe(version, suffix):
    joined = ".".join(str(part) for part in version)
    return f"{joined}-{suffix}" if suffix else joined

def patch_step(base): return (base[0], base[1], base[2] + 1)
def minor_step(base): return (base[0], base[1] + 1, 0)
def major_step(base): return (base[0] + 1, 0, 0)

def check_hotfix(base, base_suffix, head, head_suffix):
    if head_suffix != "":
        return f"a hotfix cannot carry a version suffix, found '{head_suffix}'"

    if head != patch_step(base):
        return (f"a hotfix must be exactly one patch version ahead of the base: base is at "
                f"{describe(base, base_suffix)}, so the branch should be at "
                f"{describe(patch_step(base), '')}, but it is at {describe(head, head_suffix)}")

    return None

def check_release(base, base_suffix, head, head_suffix):
    base_rc = rc_number(base_suffix, "the base branch")
    head_rc = rc_number(head_suffix, "the release branch")

    # rc.0 marks a release branch that is preparing its first candidate, so it never publishes
    if head_rc == 0:
        return ("rc.0 marks a release branch preparing its first candidate and is not "
                "publishable: bump the suffix to rc.1 before merging")

    # same version as the base: this is a further candidate, or the final release of one
    if head == base:
        if base_rc is None:
            return (f"the base is already at released {describe(base, base_suffix)}, so the "
                    "release branch has to step the version")

        # clearing the suffix turns the standing candidate into the final release
        if head_rc is None:
            return None

        if head_rc <= base_rc:
            return (f"the candidate number has to move forward: the base is at "
                    f"{describe(base, base_suffix)} and the branch is at "
                    f"{describe(head, head_suffix)}")

        return None

    # a different version: this opens a new cycle, and the step has to be a single one
    if head in (patch_step(base), minor_step(base), major_step(base)):
        return None

    return (f"a release must be exactly one patch, minor or major version ahead of the base: "
            f"the base is at {describe(base, base_suffix)} and the branch is at "
            f"{describe(head, head_suffix)}, but the only accepted steps are "
            f"{describe(patch_step(base), '')}, {describe(minor_step(base), '')} or "
            f"{describe(major_step(base), '')}")

CHECKS = {"hotfix": check_hotfix, "release": check_release}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kind", choices=sorted(CHECKS), required=True,
                        help="which set of version steps to accept")
    parser.add_argument("--base", required=True,
                        help="CMakeLists.txt as it stands on the branch being merged into")
    parser.add_argument("--head", required=True,
                        help="CMakeLists.txt as it stands on the branch being merged")
    args = parser.parse_args()

    base, base_suffix = read_version(args.base)
    head, head_suffix = read_version(args.head)

    problem = CHECKS[args.kind](base, base_suffix, head, head_suffix)

    if problem is not None:
        print(f"::error::{problem}")
        return 1

    print(f"accepted {args.kind} version step: "
          f"{describe(base, base_suffix)} -> {describe(head, head_suffix)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
