#!/usr/bin/env python3
"""Verify that a branch carries a legal version for what it is.

Pull requests into main are checked for a legal version step, so that a release or
hotfix cannot reach main without the version change its release needs. Forgetting
the bump otherwise fails silently: the release workflow finds the tag already
present and skips, producing no release and no error.

develop and release branches are checked for a legal suffix instead, since their
version does not step on every push but still has to say what the branch is for.
"""

# NOTE: this script was generated by Claude for convenience, as it serves no other
# purpose than checking version bumping rules for CI. a quick human CLEANUP would
# be nice to have sooner or later, there's lot of unnecessary complexity here

import argparse
import re
import sys

VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:-(rc\.\d+|dev))?$")
RC_RE      = re.compile(r"^rc\.(\d+)$")

DEV_SUFFIX = "dev"

def read_version(path):
    try:
        text = open(path, encoding="utf-8").read().strip()
    except OSError as err:
        sys.exit(f"could not read {path}: {err}")

    match = VERSION_RE.match(text)
    if match is None:
        sys.exit(f"invalid version '{text}' in {path} (expected x.y.z, x.y.z-rc.N or x.y.z-dev)")

    return tuple(int(part) for part in match.groups()[:3]), match.group(4) or ""

def rc_number(suffix, where):
    """The N in rc.N, or None for an empty suffix. dev is rejected before this is reached."""
    if suffix == "":
        return None

    match = RC_RE.match(suffix)
    if match is None:
        sys.exit(f"unexpected version suffix '{suffix}' on {where}")

    return int(match.group(1))

def describe(version, suffix):
    joined = ".".join(str(part) for part in version)
    return f"{joined}-{suffix}" if suffix else joined

def patch_step(base): return (base[0], base[1], base[2] + 1)
def minor_step(base): return (base[0], base[1] + 1, 0)
def major_step(base): return (base[0] + 1, 0, 0)

def check_hotfix(base, base_suffix, head, head_suffix):
    if head_suffix != "":
        return f"a hotfix cannot carry a version suffix, found '{head_suffix}'"

    if head != patch_step(base):
        return (f"a hotfix must be exactly one patch version ahead of the base: base is at "
                f"{describe(base, base_suffix)}, so the branch should be at "
                f"{describe(patch_step(base), '')}, but it is at {describe(head, head_suffix)}")

    return None

def check_release(base, base_suffix, head, head_suffix):
    # -dev belongs to develop, a release branch replaces it with rc.0 in its first commit
    if head_suffix == DEV_SUFFIX:
        return ("a release branch cannot carry the -dev suffix, it belongs to develop and is "
                "replaced with rc.0 when the release branch is opened")

    base_rc = rc_number(base_suffix, "the base branch")
    head_rc = rc_number(head_suffix, "the release branch")

    # rc.0 marks a release branch that is preparing its first candidate, so it never publishes
    if head_rc == 0:
        return ("rc.0 marks a release branch preparing its first candidate and is not "
                "publishable: bump the suffix to rc.1 before merging")

    # same version as the base: this is a further candidate, or the final release of one
    if head == base:
        if base_rc is None:
            return (f"the base is already at released {describe(base, base_suffix)}, so the "
                    "release branch has to step the version")

        # clearing the suffix turns the standing candidate into the final release
        if head_rc is None:
            return None

        if head_rc <= base_rc:
            return (f"the candidate number has to move forward: the base is at "
                    f"{describe(base, base_suffix)} and the branch is at "
                    f"{describe(head, head_suffix)}")

        return None

    # a different version: this opens a new cycle, and the step has to be a single one
    if head in (patch_step(base), minor_step(base), major_step(base)):
        return None

    return (f"a release must be exactly one patch, minor or major version ahead of the base: "
            f"the base is at {describe(base, base_suffix)} and the branch is at "
            f"{describe(head, head_suffix)}, but the only accepted steps are "
            f"{describe(patch_step(base), '')}, {describe(minor_step(base), '')} or "
            f"{describe(major_step(base), '')}")

def check_develop(head, head_suffix):
    if head_suffix != DEV_SUFFIX:
        return (f"develop must carry the -dev suffix, but it is at {describe(head, head_suffix)}. "
                "It names the next planned version while that version is being worked on, and "
                "only a release branch turns it into rc.N")

    return None

def check_release_branch(head, head_suffix):
    if head_suffix == DEV_SUFFIX:
        return (f"a release branch cannot carry the -dev suffix, but it is at "
                f"{describe(head, head_suffix)}. Opening one replaces -dev with rc.0 in its "
                "first commit")

    return None

# checks that compare against the branch being merged into
STEP_CHECKS = {"hotfix": check_hotfix, "release": check_release}

# checks that only look at the branch itself
SUFFIX_CHECKS = {"develop": check_develop, "release-branch": check_release_branch}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kind", choices=sorted(STEP_CHECKS | SUFFIX_CHECKS), required=True,
                        help="which set of version rules to apply")
    parser.add_argument("--base",
                        help="VERSION.txt as it stands on the branch being merged into "
                             "(required for hotfix and release)")
    parser.add_argument("--head", required=True,
                        help="VERSION.txt as it stands on the branch being checked")
    args = parser.parse_args()

    head, head_suffix = read_version(args.head)

    if args.kind in SUFFIX_CHECKS:
        problem = SUFFIX_CHECKS[args.kind](head, head_suffix)
        accepted = f"accepted {args.kind} version: {describe(head, head_suffix)}"
    else:
        if args.base is None:
            sys.exit(f"--base is required for a {args.kind} check")

        base, base_suffix = read_version(args.base)
        problem = STEP_CHECKS[args.kind](base, base_suffix, head, head_suffix)
        accepted = (f"accepted {args.kind} version step: "
                    f"{describe(base, base_suffix)} -> {describe(head, head_suffix)}")

    if problem is not None:
        print(f"::error::{problem}")
        return 1

    print(accepted)
    return 0

if __name__ == "__main__":
    sys.exit(main())
